common:
  storageClass: default
ingestSecret: ''
ingestSecretRef:
  name: ''
  key: mail__transport__ingest__secret
ingestBaseUrl: http://server-services/internal/mta
domains: example.com
hostname: mail.localhost
tls:
  existingSecret: ''
  certManager:
    enabled: true
    issuerName: letsencrypt-prod
    issuerKind: ClusterIssuer
dkim:
  selector: mail
  autogenerate: true
  storage:
    existingClaim: ''
    storageClassName: '{{ .Values.common.storageClass }}'
    accessMode: ReadWriteOnce
    size: 1Gi
postfix:
  image:
    registry: docker.io
    repository: boky/postfix
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  serviceType: LoadBalancer
  externalTrafficPolicy: Local
  internalNetworks:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
service:
  image:
    registry: ghcr.io
    repository: rapidmx/postfix-bridge
    tag: 1.3.0
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
